# Generated by Django 5.0 on 2023-12-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
