# Generated by Django 5.0.2 on 2024-02-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
